Check for availability of zip(1).

diff --git a/epub-create b/epub-create
--- a/epub-create
+++ b/epub-create
@@ -1,5 +1,11 @@
 #!/bin/sh
 
+if ! command -v 'zip' > /dev/null
+then
+    echo "zip(1) not found."
+    exit 1
+fi
+
 if [ -z "${EDITOR}" ]
 then
     echo 'EDITOR variable not set.'
